/*
Class Name                  : BigFilesUploaderConstants
Created by                  : Mohnish Tak
Created Date                : 10 October 2023
Last Modified By            : Mohnish Tak
Last Modification Date      : 10 October 2023
Test Class                  : 
*/
/**
 * @description This class contains all constant class variables for ImageFileUploadController class
 */
public without sharing class BigFilesUploaderConstants {
    public final static String DOCUMENT = 'Document';
    public final static String DOCUMENT_ID = 'Id';
    public final static String DOCUMENT_NAME = 'Name';
    public final static String DOCUMENT_FOLDER_ID = 'FolderId';
    public final static String DOCUMENT_URL = 'URL';
    public final static String WEB_URL_MID = '/servlet/servlet.ImageServer?id=';
    public final static String WEB_URL_O_ID = '&oid=';
}
  